# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/typeDefs/resolve_error.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/typeDefs/resolve_error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n src/typeDefs/resolve_error.proto\x12\rresolve_error*\xb1\x01\n\x0cResolveError\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x15\n\x11NAME_NOT_RESOLVED\x10\x01\x12\x0f\n\x0bINVALID_URL\x10\x02\x12\x11\n\rNOT_REACHABLE\x10\x03\x12\x0f\n\x0bUNSUPPORTED\x10\x04\x12\x0f\n\x0bHTTPS_ERROR\x10\x05\x12\x17\n\x13UNKNOWN_SCRAP_ERROR\x10\x06\x12\x18\n\x14UNKNOWN_UNFURL_ERROR\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.typeDefs.resolve_error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVEERROR']._serialized_start=52
  _globals['_RESOLVEERROR']._serialized_end=229
# @@protoc_insertion_point(module_scope)
